[package]
name = "rustun"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "A library for implementing STUN server and client asynchronously"
documentation = "https://docs.rs/rustun"
homepage = "https://github.com/sile/rustun"
repository = "https://github.com/sile/rustun"
readme = "README.md"
keywords = ["STUN", "asynchronous"]
license = "MIT"

[dependencies]
crc = "1"
slog = "1"
rand = "0.3"
fibers = "0.1"
futures = "0.1"
trackable = "0.1"
handy_async = "0.2"

[dev-dependencies]
clap = "2"
slog-term = "1"
