[package]
name = "rustun"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
fibers = "0.1"
futures = "0.1"
rand = "0.3"
byteorder = "1"
error-chain = "0.8"

[dev-dependencies]
clap = "2"
