[package]
name = "rustun"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
slog = "1"
fibers = "0.1"
futures = "0.1"
rand = "0.3"
handy_async = "0.2"
track_err = {git = "https://github.com/sile/track_err.git"}

[dev-dependencies]
clap = "2"
slog-term = "1"
