[package]
name = "rustun"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
fibers = "0.1"
futures = "0.1"
rand = "0.3"
byteorder = "1"
handy_async = "0.2"
failure = {git = "https://github.com/sile/failure.git"}

[dev-dependencies]
clap = "2"
